users:
  - username: opsgenie-test+${ platform }-${ stage }@cloudposse.com
    full_name: Opsgenie Test User
    role: User
    locale: "en_US"
    timezone: "America/New_York"

  - username: opsgenie-test+${ platform }-${ stage }-2@cloudposse.com
    full_name: Opsgenie Test User 2
    role: User
    locale: "en_US"
    timezone: "America/New_York"
